/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import Model.Stockist;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author light
 */
public class Edit extends javax.swing.JPanel {

    /**
     * Creates new form Edit
     */
    public Edit() {
        initComponents();
        addemp.add(new AddSalesman());
        showInfo();
        
        
        
    }
      //code to add content into the JTable
    public ArrayList<Stockist> salsemanList(){
        ArrayList<Stockist> sl = new ArrayList<>();
        try{
        Class.forName("com.mysql.jdbc.Driver");
            try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/i_database","root",""); Statement st = con.createStatement()) {
                ResultSet rs = st.executeQuery("Select * from stockist");
                
                while(rs.next()){
                    Stockist s = new Stockist();
                    s.setPan_number(rs.getString("pan_number"));
                    s.setName(rs.getString("full_name"));
                    s.setOrganizations_name(rs.getString("organizations_name"));
                    s.setAddress(rs.getString("address"));
                    s.setPhone_number(rs.getString("phone_number"));
                    s.setDiscount_rate(rs.getFloat("discount_rate"));
                    s.setCredit_limit(rs.getInt("credit_rate"));
                    sl.add(s);
                    
                }
               
                
            }
       
    }catch(ClassNotFoundException | SQLException e){
        System.out.println(e);
    }
        return sl;
    }
    
    private void showInfo(){
        ArrayList<Stockist> sl = salsemanList();
        DefaultTableModel model = (DefaultTableModel) salsemanInfoTable.getModel();
        Object[] n = new Object[7];
       
        for (int i = 0; i < sl.size(); i++) {
            n[0] = sl.get(i).getPan_number();
            n[1] = sl.get(i).getName();
            n[2] = sl.get(i).getOrganizations_name();
            n[3] = sl.get(i).getAddress();
            n[4] = sl.get(i).getPhone_number();
            n[5] = sl.get(i).getDiscount_rate();
            n[6] = sl.get(i).getCredit_limit();
            
            model.addRow(n);
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addemp = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        salsemanInfoTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(830, 660));

        salsemanInfoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pan Number", "Name", "Organization's Name", "Address", "Phone number", "Discount Rate", "Credit Limit"
            }
        ));
        salsemanInfoTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        salsemanInfoTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        salsemanInfoTable.setRowHeight(25);
        salsemanInfoTable.setShowVerticalLines(false);
        salsemanInfoTable.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(salsemanInfoTable);

        addemp.setViewportView(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addemp, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(addemp, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane addemp;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable salsemanInfoTable;
    // End of variables declaration//GEN-END:variables
  



}
